version: "3"

volumes:
  photon-faktory-data:
  photon-bot-data:

services:
  queue:
    image: contribsys/faktory
    volumes:
      - "photon-faktory-data:/var/lib/faktory"
    ports:
      - "127.0.0.1:7420:7420"
  bot:
    build: .
    depends_on:
      - queue
    env_file:
      - .env
    volumes:
      - "photon-bot-data:/app"