version: "3"

volumes:
  faktory:
  photon:

services:
  queue:
    image: contribsys/faktory
    volumes:
      - "faktory:/var/lib/faktory"
    ports:
      - "127.0.0.1:7420:7420"
  bot:
    build: .
    depends_on:
      - queue
    env_file:
      - .env
    volumes:
      - "photon:/app"