name: Deployment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Publish Image
        uses: elgohr/Publish-Docker-Github-Action@2.7
        with:
          name: docker.pkg.github.com/${GITHUB_REPOSITORY}
          username: ${GITHUB_ACTOR}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_names: true